import { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/navbar'

const AboutPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arkews</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="min-h-screen relative">
        <div
          className="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem] animate-pulse">
          <svg
            className="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
            viewBox="0 0 1155 678"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)"
              fillOpacity=".3"
              d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
            />
            <defs>
              <linearGradient
                id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533"
                x1="1155.49"
                x2="-78.208"
                y1=".177"
                y2="474.645"
                gradientUnits="userSpaceOnUse"
              >
                <stop stopColor="#1e40af"/>
                <stop offset={1} stopColor="#059669"/>
              </linearGradient>
            </defs>
          </svg>
        </div>

        <Navbar/>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-7">
          <h1 className="text-4xl">Acerca de nosotros</h1>
          <p className="mt-6 text-lg leading-8 text-gray-400">
            En nuestra empresa, entendemos que las ideas y proyectos de nuestros
            clientes son únicos y es por eso que nos esforzamos por brindar
            soluciones de software personalizadas y a medida. Nos apasiona
            trabajar en proyectos innovadores y estamos constantemente buscando
            nuevas formas de hacer que nuestros clientes destaquen en el
            mercado. Nuestro equipo de profesionales altamente capacitados se
            dedica a transformar las ideas de nuestros clientes en soluciones de
            software innovadoras y de alta calidad.

            Utilizamos tecnologías de vanguardia para el
            desarrollo de aplicaciones modernas y escalables. Utilizamos
            lenguajes de programación como C# y Typescript para el desarrollo de
            aplicaciones de escritorio y web, y utilizamos frameworks como React
            y ReactNative para el desarrollo de aplicaciones móviles. Además,
            utilizamos plataformas en la nube como AWS y Google Cloud para el
            alojamiento y despliegue de aplicaciones, lo que nos permite ofrecer
            soluciones flexibles y escalables a nuestros clientes. Contar con un
            equipo altamente capacitado y con amplia experiencia en el uso de
            estas tecnologías nos permite ofrecer soluciones innovadoras y de
            alta calidad a nuestros clientes.
          </p>

          <div className="mt-10">
            <h2 className="text-2xl">¿Por qué elegir nuestra empresa?</h2>
            <p className="mt-6 text-lg leading-8 text-gray-400">
              En nuestra empresa, entendemos la importancia de contar con
              soluciones de software de alta calidad y es por eso que nos
              esforzamos por brindar siempre lo mejor a nuestros clientes.
              Contamos con un equipo altamente capacitado y con amplia
              experiencia en el desarrollo de aplicaciones utilizando
              tecnologías de vanguardia, lo que nos permite ofrecer soluciones
              innovadoras y personalizadas. Además, nos esforzamos por tener una
              comunicación clara y transparente con nuestros clientes a lo largo
              de todo el proceso de desarrollo, asegurándonos de que sus
              expectativas sean siempre superadas.

              Ofrecemos una combinación única de experiencia en el desarrollo de
              software, tecnologías de vanguardia y un enfoque en la
              satisfacción del cliente. Nos esforzamos por entender tus
              necesidades y brindarte soluciones que se ajusten a tus requisitos
              específicos.
            </p>
          </div>

          <div className="mt-10">
            <h2 className="text-2xl">Características destacadas de nuestra
              empresa</h2>
            <ul
              className="mt-6 text-lg leading-8 text-gray-400 list-disc list-inside">
              <li>
                Experiencia y conocimiento: Contamos con un equipo altamente
                capacitado y con amplia experiencia en el desarrollo de
                aplicaciones utilizando tecnologías de vanguardia.
              </li>
              <li>
                Soluciones innovadoras: Nos apasiona trabajar en proyectos
                innovadores y estamos constantemente buscando nuevas formas de
                hacer que nuestros clientes destaquen en el mercado.
              </li>
              <li>
                Comunicación clara: Nos esforzamos por tener una comunicación
                clara y transparente con nuestros clientes a lo largo de todo el
                proceso de desarrollo.
              </li>
              <li>
                Atención personalizada: Brindamos soluciones de software
                personalizadas y a medida, asegurándonos de que cumplan con las
                necesidades y expectativas de nuestros clientes.
              </li>
              <li>
                Calidad del código: Priorizamos siempre la calidad del código y
                la atención al detalle en todos nuestros proyectos.
              </li>
              <li>
                Desarrollo en la nube: Utilizamos plataformas en la nube como
                AWS y Google Cloud para el alojamiento y despliegue de
                aplicaciones, lo que nos permite ofrecer soluciones flexibles y
                escalables a nuestros clientes. Esto también nos permite brindar
                un soporte continuo y una actualización constante de las
                aplicaciones sin interrupciones para el usuario final.
              </li>
            </ul>
          </div>

          <div className="mt-10">
            <h2 className="text-2xl">¿Estás listo para llevar tu negocio al
              siguiente nivel con una aplicación moderna y escalable?</h2>
            <p className="mt-6 text-lg leading-8 text-gray-400">
              Si estás listo para transformar tu idea en una solución de
              software innovadora, ¡no dudes en contactarnos! Estamos dispuestos
              a trabajar contigo para entender tus necesidades y ofrecerte una
              solución personalizada que se adapte a ellas. Nuestro equipo de
              profesionales altamente capacitados está listo para ayudarte a
              hacer realidad tu proyecto de software. ¡No esperes más y
              contáctanos hoy mismo!
            </p>
          </div>

          <div className="mt-10">
            <h2 className="text-2xl">
              ¿Por qué la importancia de aplicaciones modernas es escalables?
            </h2>
            <p className="mt-6 text-lg leading-8 text-gray-400">
              Las aplicaciones modernas y escalables son esenciales para
              cualquier negocio en la actualidad. Esto se debe a que en un mundo
              cada vez más competitivo, es fundamental contar con herramientas
              que permitan adaptarse de manera rápida y eficiente a los cambios
              del mercado. Las aplicaciones escalables permiten a las empresas
              hacer frente a crecimientos imprevistos y aumentos en la demanda
              sin tener que preocuparse por la capacidad limitada de la
              aplicación. Además, las aplicaciones en la nube permiten una mayor
              flexibilidad y escalabilidad, ya que esto permite a las empresas
              ajustar su uso de recursos de acuerdo a sus necesidades actuales y
              futuras. En resumen, contar con aplicaciones modernas y escalables
              es clave para poder competir en el mercado actual y asegurar el
              éxito a largo plazo del negocio.
            </p>
          </div>
        </div>
      </main>
    </>
  )
}

export default AboutPage
