import Head from 'next/head'
import { NextPage } from 'next'
import Navbar from '../components/navbar'
import Header from '../components/landing/header'
import FeaturesSection from '../components/landing/features'
import CTASection from '../components/landing/cta'
import FooterSection from '../components/landing/footer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arkews</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen relative'>
        <div className='absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem] animate-pulse'>
          <svg
            className='relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]'
            viewBox='0 0 1155 678'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'
          >
            <path
              fill='url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)'
              fillOpacity='.3'
              d='M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z'
            />
            <defs>
              <linearGradient
                id='45de2b6b-92d5-4d68-a6a0-9b9b2abad533'
                x1='1155.49'
                x2='-78.208'
                y1='.177'
                y2='474.645'
                gradientUnits='userSpaceOnUse'
              >
                <stop stopColor='#1e40af' />
                <stop offset={1} stopColor='#059669' />
              </linearGradient>
            </defs>
          </svg>
        </div>

        <Navbar />

        <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-7 lg:py-0'>
          <Header />
        </div>

        <FeaturesSection />

        <div className='max-w-9xl mx-auto px-0 sm:px-6 lg:px-8 py-10'>
          <CTASection />
        </div>

        <div className='absolute inset-x-0 top-[calc(100%-23rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-45rem)] animate-pulse'>
          <svg
            className='relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]'
            viewBox='0 0 1155 678'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'
          >
            <path
              fill='url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)'
              fillOpacity='.3'
              d='M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z'
            />
            <defs>
              <linearGradient
                id='ecb5b0c9-546c-4772-8c71-4d3f06d544bc'
                x1='1155.49'
                x2='-78.208'
                y1='.177'
                y2='474.645'
                gradientUnits='userSpaceOnUse'
              >
                <stop stopColor='#14b8a6'></stop>
                <stop offset='1' stopColor='#14532d'></stop>
              </linearGradient>
            </defs>
          </svg>
        </div>

        <FooterSection />
      </main>
    </>
  )
}

export default Home
